language: go

go:
  - 1.12.x
  - tip

git:
  depth: 1

before_install:
  - go get -t -v ./...

notifications:
  email: false

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)