// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/cyucelen/wirect/model"

// RouterDatabase is an autogenerated mock type for the RouterDatabase type
type RouterDatabase struct {
	mock.Mock
}

// CreateRouter provides a mock function with given fields: router
func (_m *RouterDatabase) CreateRouter(router *model.Router) error {
	ret := _m.Called(router)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Router) error); ok {
		r0 = rf(router)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoutersBySniffer provides a mock function with given fields: snifferMAC
func (_m *RouterDatabase) GetRoutersBySniffer(snifferMAC string) []model.Router {
	ret := _m.Called(snifferMAC)

	var r0 []model.Router
	if rf, ok := ret.Get(0).(func(string) []model.Router); ok {
		r0 = rf(snifferMAC)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Router)
		}
	}

	return r0
}
