// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/cyucelen/wirect/model"

// SnifferDatabase is an autogenerated mock type for the SnifferDatabase type
type SnifferDatabase struct {
	mock.Mock
}

// CreateSniffer provides a mock function with given fields: sniffer
func (_m *SnifferDatabase) CreateSniffer(sniffer *model.Sniffer) error {
	ret := _m.Called(sniffer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Sniffer) error); ok {
		r0 = rf(sniffer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSniffers provides a mock function with given fields:
func (_m *SnifferDatabase) GetSniffers() []model.Sniffer {
	ret := _m.Called()

	var r0 []model.Sniffer
	if rf, ok := ret.Get(0).(func() []model.Sniffer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Sniffer)
		}
	}

	return r0
}

// UpdateSniffer provides a mock function with given fields: sniffer
func (_m *SnifferDatabase) UpdateSniffer(sniffer *model.Sniffer) error {
	ret := _m.Called(sniffer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Sniffer) error); ok {
		r0 = rf(sniffer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
